<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__role</name>
   <tag></tag>
   <elementGuidId>ddba85d0-5d67-461e-aca8-c0e765fb14aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#role</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='role']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Role *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6cf1dcb0-4d27-45ea-84d2-d8006b4c495a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select ng-pristine ng-invalid ng-star-inserted ng-touched</value>
      <webElementGuid>8b5845a8-06b0-4abd-abac-8a181e1f6d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>5d2ab298-eea2-4382-baff-09af36119550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select role admin  admin  Business analyst  Developer  Integration support Staff  Patient Advisor  TestRole </value>
      <webElementGuid>4a4df180-658c-450b-8459-64ef7d10142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role&quot;)</value>
      <webElementGuid>8e5c96f9-a1a0-40c5-b2bb-fcc1c8e379e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='role']</value>
      <webElementGuid>d689a75e-0a32-43ad-b271-1a834e3000b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-email-invite/div/div[2]/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>276402a0-01a8-43a6-b1d7-239d93d5d28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>d61c3bfc-7cd8-486f-a8d9-06d503159648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite user'])[1]/preceding::select[1]</value>
      <webElementGuid>67345ef2-ca76-438c-be6d-95b4e98bd08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::select[1]</value>
      <webElementGuid>f345d3c0-1a1d-44b2-8bc1-2251ccc54a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d5542b82-2b3a-4951-ae43-b3af0592748c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'role' and (text() = 'Select role admin  admin  Business analyst  Developer  Integration support Staff  Patient Advisor  TestRole ' or . = 'Select role admin  admin  Business analyst  Developer  Integration support Staff  Patient Advisor  TestRole ')]</value>
      <webElementGuid>8f348bad-bcbb-43b8-aa09-d3edd1096b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
