<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tile_RecordsReceivedinFinalCount</name>
   <tag></tag>
   <elementGuidId>8d7f1c87-553a-4ea1-a4ae-4607c8ce1dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-home/abp-page/div[2]/div/div[2]/div/div[4]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;62537&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>082e9385-b6c3-4b89-a8ff-c009be3a721f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold ng-star-inserted</value>
      <webElementGuid>94d51ad7-9654-4039-a0df-1de6f85130c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>62537</value>
      <webElementGuid>68f7cf34-b8f9-4d7e-b1e3-49ba1b9cf2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container&quot;]/div[@class=&quot;lpx-content&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/abp-page[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-md-3x ng-star-inserted&quot;]/div[@class=&quot;card text-center shadow-sm border-0 tile h-100 bouncy-tile bg-light-green&quot;]/div[@class=&quot;card-body&quot;]/h4[@class=&quot;fw-bold ng-star-inserted&quot;]</value>
      <webElementGuid>8aefb85a-314b-44d9-a9ee-2242a3f18acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-home/abp-page/div[2]/div/div[2]/div/div[4]/div/div/h4</value>
      <webElementGuid>6312c3e2-6e0e-4f7d-9f11-31bbfb7cd715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::h4[4]</value>
      <webElementGuid>4dd48d60-ee09-429a-ba64-079249fad216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::h4[4]</value>
      <webElementGuid>77cb24e8-f816-4212-a1d7-31475cf7aad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::h4[12]</value>
      <webElementGuid>8cec42af-8bc6-4207-b378-0ca65304dd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/preceding::h4[12]</value>
      <webElementGuid>42de87b7-03af-4052-903d-d1c1da40764b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='62537']/parent::*</value>
      <webElementGuid>6a8752a0-dd5d-4f72-9f67-7cf46b47980a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/h4</value>
      <webElementGuid>80d13465-80a8-4a30-bc08-2e12b9514cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '62537' or . = '62537')]</value>
      <webElementGuid>f4bd3f5e-6739-44cc-8987-700931c0a789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
