<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tile_RecordsReceivedinFinalCount</name>
   <tag></tag>
   <elementGuidId>8d7f1c87-553a-4ea1-a4ae-4607c8ce1dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/app-root[1]/abp-dynamic-layout[1]/abp-application-layout[1]/lpx-layout[1]/div[1]/div[2]/div[2]/app-home[1]/abp-page[1]/div[2]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/h4[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;62537&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>348bdded-3a54-417e-80c3-78379a87ad9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold ng-star-inserted</value>
      <webElementGuid>f9177b36-e783-427c-8855-33015538138e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>62537</value>
      <webElementGuid>4ac9ad75-c8c1-4b65-b822-5bd78cfc49d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container&quot;]/div[@class=&quot;lpx-content&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/abp-page[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-md-3x ng-star-inserted&quot;]/div[@class=&quot;card text-center shadow-sm border-0 tile h-100 bouncy-tile bg-light-green&quot;]/div[@class=&quot;card-body&quot;]/h4[@class=&quot;fw-bold ng-star-inserted&quot;]</value>
      <webElementGuid>44073b3f-1d44-4fae-8f26-c9663feeaa41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-home/abp-page/div[2]/div/div[2]/div/div[4]/div/div/h4</value>
      <webElementGuid>8b51f32c-030e-4a58-983d-7b62e1591210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::h4[4]</value>
      <webElementGuid>8c0f4cef-4724-4abd-98a9-5906e77d0c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::h4[4]</value>
      <webElementGuid>3d6fad63-3df3-4046-8b9b-2c1faedb25fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::h4[12]</value>
      <webElementGuid>0d1305f3-19af-4baa-b269-289a78e53256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/preceding::h4[12]</value>
      <webElementGuid>052dc870-8b76-41c0-91d5-34e754c2122e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='62537']/parent::*</value>
      <webElementGuid>c151f801-a106-4962-962e-f02d41943c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/h4</value>
      <webElementGuid>d5a0193b-b0c1-442f-819e-b1926a1e0b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '62537' or . = '62537')]</value>
      <webElementGuid>c76e6c30-cea5-4fca-8509-20e148b01ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
