<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>415ed909-ddce-46a4-bd3a-f0a4972719f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#passwordInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>731e5f60-02a9-4a72-a889-b370143f0860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>82424d0e-b51e-4b8a-a135-0a002815a302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordInput</value>
      <webElementGuid>a4db6ca0-fd4b-4cf9-aa48-bae77b33c976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0d063296-c46b-4df6-90c8-a2e26eb6e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6be3876f-9dbf-4e4b-be51-d3dafc404019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Password must be a string with a maximum length of 128.</value>
      <webElementGuid>4f0fb247-9bec-49ce-b6c7-c240eaec13e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>fef2aa7e-2c65-41c4-8270-8ddcf8a24c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Password field is required.</value>
      <webElementGuid>f54b330e-d36a-4d92-8467-13855cbf9dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>817b7ffb-483d-4182-8783-71025d3a7abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginInput.Password</value>
      <webElementGuid>7f13b93c-3714-453d-b652-d8e702d2e6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordInput&quot;)</value>
      <webElementGuid>0b8067c7-17ff-4047-accd-c1dff6758b0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordInput']</value>
      <webElementGuid>a1f0c1a8-daad-4716-9305-805a5e178444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>833d4661-34c8-42aa-bfc8-b71e69d3cbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6d946a7e-7e3f-4541-8d06-cea55be81051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passwordInput' and @type = 'password' and @name = 'LoginInput.Password']</value>
      <webElementGuid>3065d93a-f7c5-4a55-8f3e-86d0d49264f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
