<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Roles_ngb-nav-0-panel</name>
   <tag></tag>
   <elementGuidId>8eca5db1-cdbc-464f-83fb-e013c7e85cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ngb-nav-0-panel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ngb-nav-0-panel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;User Information&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35b4bf97-e5b1-400c-9d77-45a261493a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-pane fade show active ng-star-inserted</value>
      <webElementGuid>77350dc3-30e8-4e4b-8ca1-714245e3d01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngb-nav-0-panel</value>
      <webElementGuid>b36d8691-a78a-4d82-ac6c-9dca329c3e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>93631445-80b3-410b-b735-d1f15b2853c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ngb-nav-0</value>
      <webElementGuid>5fa9d177-4e92-45b6-b330-dfce157a36cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> User name  *  Password  *  Name    Surname    Email address  *  Phone number    Active    Account lockout   </value>
      <webElementGuid>0ff415c7-1361-4688-8780-1f13ee7776a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-nav-0-panel&quot;)</value>
      <webElementGuid>c4b3240d-ced1-414e-b36a-78d7febeccab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ngb-nav-0-panel']</value>
      <webElementGuid>c4e07c04-34f4-4e1e-bfc3-bb8aa49ec419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='abp-modal-body']/form/div/div</value>
      <webElementGuid>670b8b05-cc34-447c-93cf-063496037c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[2]/following::div[2]</value>
      <webElementGuid>d51dfa2e-8946-4c7b-a9eb-82eddf6651d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Information'])[1]/following::div[2]</value>
      <webElementGuid>283ce306-565d-4f0d-87c1-e6719160f98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>cdf46c6a-c97f-4d85-b5f6-0fba1f1959ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ngb-nav-0-panel' and (text() = ' User name  *  Password  *  Name    Surname    Email address  *  Phone number    Active    Account lockout   ' or . = ' User name  *  Password  *  Name    Surname    Email address  *  Phone number    Active    Account lockout   ')]</value>
      <webElementGuid>d76ed33e-681c-4617-b2ff-5d13efe53efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
