<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Roles_form-check-label ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>a3286def-3c6b-4792-88d6-251d53445e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ngb-nav-1-panel']/div/abp-checkbox/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;admin&quot;s >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5dc8bb2d-b0c6-4229-9d5f-df2948379b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>roles-0</value>
      <webElementGuid>b115f129-d402-4961-af44-f53ce582cdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label ng-star-inserted</value>
      <webElementGuid>00232658-c5bd-4480-855c-ba50bccfd46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> admin </value>
      <webElementGuid>a2e36b6f-dafb-4e35-a863-1e58767d98d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-nav-1-panel&quot;)/div[@class=&quot;form-check mb-2 ng-star-inserted&quot;]/abp-checkbox[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;form-check-label ng-star-inserted&quot;]</value>
      <webElementGuid>1f0b014d-8dd0-4880-8eb5-3b63a5f0fb88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngb-nav-1-panel']/div/abp-checkbox/div/label</value>
      <webElementGuid>2d73fd14-c3d5-4593-ba95-67656edad80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[2]/following::label[1]</value>
      <webElementGuid>63bb47a9-9708-4a02-8a88-cdb9c32dab60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Information'])[1]/following::label[1]</value>
      <webElementGuid>e29de133-2d66-49c8-bd29-95b79a4c8347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[5]/preceding::label[1]</value>
      <webElementGuid>78be927e-6769-4654-bde8-5f7e787b9ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business analyst'])[1]/preceding::label[2]</value>
      <webElementGuid>97847849-97b3-4dbf-855d-8e1532ceae03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//abp-checkbox/div/label</value>
      <webElementGuid>80a6a974-383a-472f-8370-6420a88995f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' admin ' or . = ' admin ')]</value>
      <webElementGuid>5af12cd1-67be-44c8-b769-591eba33f2e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
