<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Forgot password_Action</name>
   <tag></tag>
   <elementGuidId>b7a712fe-fd98-4f13-b225-1496a198ab69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;Action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51c59dc4-0d54-457f-bfe1-c8a0752ee71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e47253cb-7251-484d-8a0e-af9f7c2d5289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>a07a18cf-862d-44d2-98b5-031912785b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>be287dcd-ffc2-4048-a975-7b557261b7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-block w-100 btn btn-primary btn-lg</value>
      <webElementGuid>5f4d31d7-6a01-4494-ba57-2fe8305bde4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-busy-text</name>
      <type>Main</type>
      <value>Processing...</value>
      <webElementGuid>ceb12fcb-2ed8-4665-92e9-77b7bb591805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>1f5c46a7-e97b-4777-bbb7-a4b084393d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container m-0&quot;]/div[@class=&quot;lpx-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-lg-5 mx-auto&quot;]/div[@class=&quot;abp-account-container&quot;]/div[@class=&quot;card shadow-sm logincard&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;my-2&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn-block w-100 btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>120e310d-0bce-4f4c-bb8a-dd2f3e7b706f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='Action']</value>
      <webElementGuid>6614227d-25d4-40a5-9f0c-85e57b30b90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div[4]/button</value>
      <webElementGuid>5aa919b7-b5d0-4e92-866d-b565908970eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>728bad3f-2259-4a8e-bd72-95bf4b358bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>e1b90166-133b-4932-802b-ec1ea59b8c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'Action' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>e9908c94-5d52-4800-88fe-2de04a6a50f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
