<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_LoginInput_UserNameOrEmailAddress</name>
   <tag></tag>
   <elementGuidId>3c0f1564-96ad-49bf-a9a6-7afd7a7a1ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd27368d-b498-4ebd-9d00-4c7cba7c5277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5271ec34-af68-4796-8e4c-5ef2e3d2eba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edbf2ce3-f34f-492d-b2b1-b98dbdbbac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e61c0f3b-5911-4e86-805c-1c2642be7196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Username or email address must be a string with a maximum length of 256.</value>
      <webElementGuid>2efbc621-5da6-46e5-a0da-2a5ecc85ac08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>0866a1c7-797a-4e55-b478-2158b7d1802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Username or email address field is required.</value>
      <webElementGuid>0c08fdca-6a1e-4562-a390-d1ac58408d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginInput_UserNameOrEmailAddress</value>
      <webElementGuid>b3195c32-b4ac-491e-80e9-ca6b3929d9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>c259cefd-0a68-462f-a46d-f4313aca5b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginInput.UserNameOrEmailAddress</value>
      <webElementGuid>a1b95b77-7998-4cca-a8a6-8507a0ae535e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginInput_UserNameOrEmailAddress&quot;)</value>
      <webElementGuid>765259e7-69b9-481a-a1a5-43c356432151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      <webElementGuid>c11d4f88-fb8a-4f03-a837-20a6bdd59089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div/input</value>
      <webElementGuid>90ed3c37-ba5f-4a61-b9e1-463c0099b078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>20f6706e-2e69-4c85-aa43-d85d8a162776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoginInput_UserNameOrEmailAddress' and @name = 'LoginInput.UserNameOrEmailAddress']</value>
      <webElementGuid>e249ef40-d117-42ab-b039-fd7eafb0f41a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
