<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Is Integration Enabled_toggle</name>
   <tag></tag>
   <elementGuidId>e68f151a-8e9e-4e31-bb38-f5afafa85da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexSwitchCheckChecked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexSwitchCheckChecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Is Integration Enabled&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>213532a9-02b4-4cd1-94fc-e7c8ebaa3050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dcafb884-60af-420c-8605-152d88f870ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexSwitchCheckChecked</value>
      <webElementGuid>fc450a6a-af45-48bd-9403-ae1f40367be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isIntegrationEnabled</value>
      <webElementGuid>f73d9477-8ab9-412a-90a0-996873f6c1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9a997a4e-a7c3-4d4c-9b90-5537fd54a408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexSwitchCheckChecked&quot;)</value>
      <webElementGuid>04cbf7d6-739f-41b9-aeb5-b5d0a5bde460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexSwitchCheckChecked']</value>
      <webElementGuid>e0ec5dc3-ef22-411b-8c6d-6cff575c50eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-add-hospital-location/form/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>28ca5913-95bd-4094-b306-c8a48d537683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>69f55c79-eb53-4472-9c77-0de838e49620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexSwitchCheckChecked']</value>
      <webElementGuid>1f887471-d594-4f37-b132-b1302de4ec45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
