<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationNameTextBox</name>
   <tag></tag>
   <elementGuidId>7bea53b1-9bef-41ab-8e96-8efa4a278732</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'hospital/location...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-valid.ng-touched.ng-dirty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;hospital/location...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1ecaaa2-36f5-49b2-9dc6-d8146b5a8163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed012eb2-10b6-4c92-b375-7dd8072e14e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>hospital/location...</value>
      <webElementGuid>c10653f7-8f55-4b2d-b24d-9f982ac7f012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-touched ng-dirty</value>
      <webElementGuid>1d5afb47-f833-4a06-b38b-d0ae1207d957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container&quot;]/div[@class=&quot;lpx-content&quot;]/app-hospital-location-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;row justify-content-between&quot;]/div[@class=&quot;d-flex w-fit justify-content-end align-items-center gap-2 flex-wrap&quot;]/div[@class=&quot;input-group input-group-sm w-auto&quot;]/input[@class=&quot;form-control ng-valid ng-touched ng-dirty&quot;]</value>
      <webElementGuid>a7eba56e-ddce-4ee1-ba0a-a726aa9dd764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>11ad2585-2139-4002-9b8c-d3bb22cca3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-hospital-location-list/div/div/div/div[2]/div/input</value>
      <webElementGuid>bbd23915-4064-452c-814b-b75ef0d00212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-hospital-location-list/div/div/div/div[2]/div/input</value>
      <webElementGuid>515f203e-a3c0-456c-9d87-0b3c4f8b30a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'hospital/location...']</value>
      <webElementGuid>1451c6ae-5521-443f-a287-4d39bb74ee67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
