<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationDropdownCheckbox</name>
   <tag></tag>
   <elementGuidId>94120281-a6a5-4f1d-9557-34a5db565d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hospital_b8817407-cfea-2b38-9992-3a199d2d7e84</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hospital_b8817407-cfea-2b38-9992-3a199d2d7e84']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hospital_b8817407-cfea-2b38-9992-3a199d2d7e84</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>652749a5-69d3-46a0-b119-dce71883b668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dd4653be-0a35-4318-8ecd-e8486e42dace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>138b84a9-7c5c-41f9-845b-24dfcfa08bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hospital_b8817407-cfea-2b38-9992-3a199d2d7e84</value>
      <webElementGuid>719544a6-d33a-4979-8bb5-62cb635eab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hospital_b8817407-cfea-2b38-9992-3a199d2d7e84&quot;)</value>
      <webElementGuid>0d172a90-ca10-44b2-8d7c-50290db6c605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hospital_b8817407-cfea-2b38-9992-3a199d2d7e84']</value>
      <webElementGuid>e2c56ed0-8a82-4d96-8df6-e3d85a7f6fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div/div/div[2]/lpx-toolbar-container/lpx-toolbar/lpx-toolbar-items/lpx-toolbar-item/div/div/div/app-dropdown-control/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>5b705f8b-595b-4170-82ab-4a19157cafd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e022beaf-8905-4cf7-ac3d-0e2b809a5953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hospital_b8817407-cfea-2b38-9992-3a199d2d7e84']</value>
      <webElementGuid>7d2e57ce-80b2-44e5-a97a-9b3ac63c0833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
