<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationDropwon_Apply_Button</name>
   <tag></tag>
   <elementGuidId>0aacdb3d-5edb-4782-b3a5-29c0097422cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da10243a-1ed3-418c-a00c-3babb6e9cf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>849080e6-70a1-49c0-9013-116df361dfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>66db2f42-8045-46f0-8ac9-695c7cb59b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>69d94bbe-5ed0-4232-a652-d0254a1f486b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container&quot;]/div[@class=&quot;lpx-topbar-container&quot;]/div[@class=&quot;lpx-topbar&quot;]/div[@class=&quot;lpx-topbar-content ng-star-inserted&quot;]/lpx-toolbar-container[@class=&quot;ng-star-inserted&quot;]/lpx-toolbar[1]/lpx-toolbar-items[@class=&quot;lpx-topbar-content&quot;]/lpx-toolbar-item[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;lpx-menu-item-link ng-star-inserted&quot;]/div[@class=&quot;lpx-menu-item-icon&quot;]/div[@class=&quot;lpx-icon&quot;]/app-dropdown-control[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dropdown ng-star-inserted&quot;]/div[@class=&quot;dropdown-menu p-2 hospital-dropdown show&quot;]/div[@class=&quot;d-flex justify-content-between mt-3&quot;]/button[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>7fb18a91-7083-4282-b218-319d751549a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>4e0d5795-2921-43d1-9ae8-2558ae705701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div/div/div[2]/lpx-toolbar-container/lpx-toolbar/lpx-toolbar-items/lpx-toolbar-item/div/div/div/app-dropdown-control/div/div/div[3]/button</value>
      <webElementGuid>41bc5d88-35d7-4d21-bf26-957b0c6c5c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loc'])[1]/following::button[1]</value>
      <webElementGuid>0d5fd81a-820f-44fe-8e31-4716ecbea098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/following::button[1]</value>
      <webElementGuid>56b523df-5b7e-44f8-842a-e62f57bd0798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>c7874a88-cc4f-46ed-b67b-d28a64504a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::button[2]</value>
      <webElementGuid>8fba67e2-9007-4b10-a975-9448dd24cd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>b02722b4-d4a9-4902-b643-72f507454e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>0bc92f4f-e462-4a5e-98be-378801ede42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>65be32af-4e67-4cb7-acb7-1e0943fe7e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
