<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_LoginInput_UserNameOrEmailAddress</name>
   <tag></tag>
   <elementGuidId>08860525-86d7-46de-911c-75361ba4a89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a201e48-1f2c-4f86-a378-aace28fbb29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>78a1e0c7-fa6e-4bcf-bf86-0d0916b171d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1390431d-a067-4f38-a3d3-5b385b7ad9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b5c950c-3591-445b-96ee-a6cb38416db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Username or email address must be a string with a maximum length of 256.</value>
      <webElementGuid>2bb931bd-2105-40f0-b78a-8e37f69f5c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>f5e82f9c-5f93-400d-8fd6-92d6bccbeb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Username or email address field is required.</value>
      <webElementGuid>c8dae3e4-64a9-40b1-a299-58f84854d227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginInput_UserNameOrEmailAddress</value>
      <webElementGuid>dd81528f-0171-416c-bc6e-110c10e0c34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>c91dfe9e-8276-4543-990a-e5a6b14e19f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginInput.UserNameOrEmailAddress</value>
      <webElementGuid>8cc790e4-6e7e-44b2-abcc-202a18a7331a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginInput_UserNameOrEmailAddress&quot;)</value>
      <webElementGuid>dd23be89-4168-4fd4-a0e2-8803e0ab0aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      <webElementGuid>8bfeb3a2-9c83-4be5-8041-f4a9d0733317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div/input</value>
      <webElementGuid>c77ae7c6-9288-4d0a-a434-58a70a7630a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4801a28c-f627-4737-adb2-fcfc4bd314f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoginInput_UserNameOrEmailAddress' and @name = 'LoginInput.UserNameOrEmailAddress']</value>
      <webElementGuid>13ffddee-4937-432e-9854-649ecab8cb5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
