<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_LoginInput_UserNameOrEmailAddress</name>
   <tag></tag>
   <elementGuidId>35feb113-1352-4a3d-8423-13c3a7c8c744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3618f818-85f7-4a18-8c42-6dc3663941d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66d93fc8-ccc7-47ae-a793-7250ea8be7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fb5a7bb-a655-4179-957c-406f3fbbf63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80fc0fd4-732e-428e-8fbb-888920368005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Username or email address must be a string with a maximum length of 256.</value>
      <webElementGuid>373aa190-a69b-4053-8619-35d264f022f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>3bc27d20-e5ce-4383-9bb8-830907c27952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Username or email address field is required.</value>
      <webElementGuid>097799eb-b101-4d9e-b8ea-ac523ec8c3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginInput_UserNameOrEmailAddress</value>
      <webElementGuid>73d5af43-0127-4b03-a9b3-aed6a0203b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>7cb1673f-9eab-47ed-ad9a-80209201c4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginInput.UserNameOrEmailAddress</value>
      <webElementGuid>e36a8adb-5a21-4e52-b212-b45d7293bd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginInput_UserNameOrEmailAddress&quot;)</value>
      <webElementGuid>d022331d-56d9-4e40-a95b-bd44b14a90e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      <webElementGuid>ece90ad4-8b78-46a2-a62a-3180b46e79c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div/input</value>
      <webElementGuid>4cf11e4c-8547-4b6d-bc7e-43f16e4e6294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>39c25b34-d889-4f24-91d0-57897304c675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoginInput_UserNameOrEmailAddress' and @name = 'LoginInput.UserNameOrEmailAddress']</value>
      <webElementGuid>a440f592-d932-4cfb-bb5f-d6ae99a94e68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
