<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Is Integration Enabled_Toggle</name>
   <tag></tag>
   <elementGuidId>f6b6a52b-4d1a-414d-a2cb-f24261a80aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexSwitchCheckChecked']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flexSwitchCheckChecked</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Is Integration Enabled&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5270543c-3b94-4e74-9e2c-42a0d65c6808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f82f33c5-b23f-4176-b7dc-4c2bb20779b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexSwitchCheckChecked</value>
      <webElementGuid>ffe7f967-0cf1-4041-b92a-c6c90a879581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isIntegrationEnabled</value>
      <webElementGuid>14b537d4-4f52-42e3-95c1-17002bb40631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cd483f01-2841-434c-aeeb-7a13871e10af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexSwitchCheckChecked&quot;)</value>
      <webElementGuid>34fe4991-6464-430b-9a4d-03948c578fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexSwitchCheckChecked']</value>
      <webElementGuid>449da8ff-9b69-4243-b7e0-0083a9916ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/app-add-hospital/form/div/div[2]/div/div[6]/div/input</value>
      <webElementGuid>1565bdd6-97c1-4549-95ec-f2ef8ebb6c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/input</value>
      <webElementGuid>e108d4c1-97fe-468b-af48-166200fe709d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexSwitchCheckChecked']</value>
      <webElementGuid>eb651b81-4b76-4817-b1c1-4ac2f13b8772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
