<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Forgot password_Action</name>
   <tag></tag>
   <elementGuidId>bfd6f312-19b3-41bb-a091-39a4dfcd7080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;Action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f560b85-5b04-403e-8c32-16a6061bf135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d17971a9-b748-4680-b3d0-7c8d1f0b0549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>45c28a6c-6d1d-4a0e-a39b-b889c1a06df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4112f3a4-0c90-4c12-92c4-693db7cbba80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-block w-100 btn btn-primary btn-lg</value>
      <webElementGuid>36b0ad68-14cf-4d85-8a72-ed01e0f47f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-busy-text</name>
      <type>Main</type>
      <value>Processing...</value>
      <webElementGuid>9582e660-d56a-4676-89e3-662c0cf4d17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c6b9f155-42cd-44e4-a329-b801d433082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpx-wrapper&quot;)/div[@class=&quot;lpx-content-container m-0&quot;]/div[@class=&quot;lpx-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-lg-5 mx-auto&quot;]/div[@class=&quot;abp-account-container&quot;]/div[@class=&quot;card shadow-sm logincard&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;my-2&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn-block w-100 btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>b6846c27-8e6d-4518-a76e-0e78db82d82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='Action']</value>
      <webElementGuid>5e902549-eb35-4f10-bd77-632f0fbb51e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lpx-wrapper']/div[2]/div[2]/div/div/div/div/div/div/form/div[4]/button</value>
      <webElementGuid>5d081087-08d0-4e57-9802-5c4827251949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>cbec39c7-388f-4c7a-a3b6-a9153b9603ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>5c114e76-3fb1-41ed-8331-ddcbbd69def3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'Action' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>3de7688f-2fd3-4932-a6a4-b0276ec86c03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
